name: Deploy to Local IIS

on:
  push:
    branches:
      - master  # veya kullanmak istediğiniz varsayılan dal adı

jobs:
  build-and-deploy:
    runs-on: windows-latest  # Windows çalışma ortamı

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '4.x'  # ASP.NET Framework 4.x sürümüne uygun .NET sürümü

    - name: Build and Publish
      run: |
        # ASP.NET Framework projenizi derleyin
        msbuild /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true

    - name: Deploy to IIS
      run: |
        # Yayınladığınız dosyaları IIS'in belirlediğiniz sitesine kopyalayın
        Copy-Item -Path "C:\www\gh-cd-demo.com" -Destination "C:\inetpub\wwwroot\gh-cd-demo.com" -Recurse -Force

      # Opsiyonel: Eğer IIS App Pool'unu yeniden başlatmak isterseniz
    - name: Restart IIS App Pool
      run: |
          iisreset /ap "gh-cd-demo.com"
