name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1


    - name: Restore NuGet packages
      run: nuget restore DevingOps.sln

    - name: Build the Solution
      run: msbuild DevingOps.csproj /p:Configuration=Release /p:DeployOnBuild=true


    
