
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: windows-latest
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.0
  
    - name: Restore NuGet Packages
      run: nuget restore path/to/your/DevingOps.sln
  
    - name: Build
      run: msbuild path/to/your/DevingOps.sln /p:Configuration=Release
  
    - name: Publish to IIS
      run: msdeploy -verb:sync -source:package=$(System.DefaultWorkingDirectory)www\gh-cd-demo.com -dest:auto,computerName='http://gh-cd-demo.com:81/',username='gokse',password='160610',authtype='basic',includeAcls='False'
