
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore DevingOps.sln

    - name: Build Web App
      run: msbuild DevingOps.sln /p:Configuration=Release

    - name: Publish to IIS
      run: C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe -verb:sync -source:package=$(System.DefaultWorkingDirectory)/www\gh-cd-demo.com.zip -dest:auto,computerName='http://gh-cd-demo.com:81/',username='gokse',password='160610',authtype='basic',includeAcls='False'

