
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore DevingOps.sln

    - name: Build the Solution
      run: msbuild DevingOps.sln /p:Configuration=Release

    - name: SmarterASP.NET Web Deploy
  # You may pin to the exact commit or the version.
  # uses: jahbenjah/SmarterASP.NET-web-deploy@845c19cd4b003b854908a1008b34fe97e98a56b1
      uses: jahbenjah/SmarterASP.NET-web-deploy@1.0.0.alpha.8
      with:
    # IIS website name
        website-name: ${{ secrets.WEBSITE_NAME }}
    # IIS server computer name
        server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
    # IIS server username
        server-username: 
    # IIS server password
        server-password: 
    # The source directory for payload
        source-path: # optional, default is \publish\
    # The target directory for payload
        target-path: # optional, default is ""
    # Delete files on the destination computer that do not exist on the source computer
        target-delete: # optional, default is false
            
    - name: Restart IIS
      shell: cmd
      run: |
        iisreset /stop
        iisreset /start
