name: Test

on:
  push:
    branches: master

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        vswhere-path: 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\'


    - name: Build Solution
      run: |
        msbuild.exe DevingOps.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployMethod:FolderMethod /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release"

