name: Test

on:
  push:
    branches: master

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        vswhere-path: 'C:\Program Files (x86)\Microsoft Visual Studio\Installer'


    - name: Build Solution
      run: |
        msbuild.exe 'C:\Users\gokse\Desktop\Everything\Udemy Projeler\DevingOps\DevingOps.sln' /p:DeployOnBuild=True /p:configuration="Release" /p:PublishProfile='C:\Users\gokse\Desktop\Everything\Udemy Projeler\DevingOps\Properties\PublishProfiles\FolderProfile.pubxml'

